### ISSUE TITLE
Docker authentication to private registry fails since 1.3.4

### ISSUE THREAD

**Issue by stephanedaviet** [spotify/dockerfile-maven#62]
I have upgraded to 1.3.4 to benefit from the flag `googleContainerRegistryEnabled`, but I encounter the following exception:
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.4:push (push-docker-image) on project sample: Could not push image: no basic auth credentials -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.4:push (push-docker-image) on project sample: Could not push image
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not push image
	at com.spotify.plugin.dockerfile.PushMojo.execute(PushMojo.java:90)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:227)
	at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:216)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 31 more
Caused by: com.spotify.docker.client.exceptions.DockerException: no basic auth credentials
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.handleError(LoggingProgressHandler.java:105)
	at com.spotify.plugin.dockerfile.LoggingProgressHandler.progress(LoggingProgressHandler.java:63)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:74)
	at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1291)
	at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1271)
	at com.spotify.plugin.dockerfile.PushMojo.execute(PushMojo.java:88)
	... 35 more
```

I have a quite standard `config.json`:
```javascript
{
	"auths": {
		"nexus-fabfonc.localdomain:5000": {
			"auth": "YWRtaW46YWRtaW4xMjM="
		},
		"nexus-fabfonc.localdomain:5001": {
			"auth": "YWRtaW46YWRtaW4xMjM="
		}
	}
}
```

I have also tested with a duplicated one like below with and without protocols as I stumbled on old issues linked to that problem, but with no more success, idem with only protocol suffixed ones:
```javascript
{
	"auths": {
		"http://nexus-fabfonc.localdomain:5000": {
			"auth": "YWRtaW46YWRtaW4xMjM="
		},
		"http://nexus-fabfonc.localdomain:5001": {
			"auth": "YWRtaW46YWRtaW4xMjM="
		},
		"nexus-fabfonc.localdomain:5000": {
			"auth": "YWRtaW46YWRtaW4xMjM="
		},
		"nexus-fabfonc.localdomain:5001": {
			"auth": "YWRtaW46YWRtaW4xMjM="
		}
	}
}
```

I thinks that it is linked to the upgrade of the Docker client from 8.8.0 to 8.8.1 introduced by c295836810b9ad80c00361daf3bcf702d967e2d0 to resolve #23. I suspect more specifically the commit https://github.com/spotify/docker-client/commit/c29e44bc986d108b40862ee0b540b7a943f9c424.

**Comment by stephanedaviet** [comment]
Small problem, we haven't HTTPS on the target internal server :-/. I am hardly working to get it set up. Thanks for the hint though.

**Comment by ldebat** [comment]
+1
Using an unsecured private Nexus 3 (http).
I had to go back to v1.3.3 (and ~/.docker/config.json without transfer protocol)

**Comment by bigtoast** [comment]
+1
Using an amazon container registry and auth failed with the above error for 1.3.5. Rolling back to 1.3.3 worked.

**Comment by bkmeneguello** [comment]
+1
I'm using Jenkins pipeline withDockerRegistry with Nexus3 private http repository. This issue is realling disturbing my builds.

**Comment by j-tim** [comment]
Same issue here using Gitlab CI build pipelines as well.
I'll stick with version 1.3.3 for now otherwise my build will break...

**Comment by bkmeneguello** [comment]
1.3.6 with settings.xml server authentication works very well for me.

Em 23 de set de 2017 16:31, "Tim van Baarsen" <notifications@github.com>
escreveu:

**Comment by nahguam** [comment]
+1
We're using AWS ECR, doing `eval $(aws ecr get-login ...)` prior to `mvn deploy` and get the same error with 1.3.6. Tried 1.3.3 as suggested by @bigtoast and this works.

**Comment by uvwild** [comment]
so the thing looks really broken. 
Requiring a dot in the hostname is something that should be documented. 
Considering the spotify use cases this is understandable though.

But then it becomes impossible when using local insecure-registries. 
Which I think makes totally sense in networks without an internet connection!

If I specify the protocol the ImageRef parser fails.
If I dont specify the protocl HTTPS get chosen.... 
so no way to get this going. 

I try maven auth now.

**Comment by uvwild** [comment]
So I found a super messy workaround:
I still can use the simple host insecure docker registry (our local nexus server).
BUT I need to add a **fake** authentication line to the .docker/config.json by copying the authentication line from the real server and replacing the host with the **default** docker repo like so:
```
"auths": {
		"my-local-nexus-host": {
			"auth": "XXXXXXXXXXXXXXXXXXX"
		},
		"https://index.docker.io/v1/": {
			"auth": "XXXXXXXXXXXXXXXXXXX"
		},
}
```

**Comment by res1st** [comment]
Same  problem for me, I stick to 1.3.3 until it is solved.

**Comment by mryan43** [comment]
This is fixed in the docker-client library in newer versions. You can force the dependency in the plugin like this : 
```
<plugin>
...
<dependencies>
  <dependency>
    <groupId>com.spotify</groupId>
    <artifactId>docker-client</artifactId>
    <classifier>shaded</classifier>
    <version>8.10.0</version>
  </dependency>
</dependencies>
</plugin>

**Comment by bentatham** [comment]
Note that while docker-client:8.10.0 fixes the problem, there are other classpath issues if you try to use docker-client:8.11.0 due to other refactoring between libraries.  So stick with 8.10.0.

**Comment by helt** [comment]
I use gitlab-ci and sonatype nexus 3, dockerfile 1.3.6
Thanks to @mryan43 for the docker-client hint

secret variables are defined in gitlab: DOCKER_PUSH_USER and DOCKER_PUSH_PASS

I know the excerpt below is not MWE, but maybe it still helps someone to work around this issue

.gitlab-ci.yml:
```
build:
  image: openjdk:8-jdk
  stage: build
  script:
    - ./mvnw -B  -s .ci/settings.xml clean install deploy site-deploy 
```

.ci/settings.xml
```
<servers>
    <server>
        <!-- for docker push -->
        <id>docker.nexus.somewhere</id>
        <username>${env.DOCKER_PUSH_USER}</username>
        <password>${env.DOCKER_PUSH_PASS}</password>
    </server>
</servers>
```

pom.xml
```
<project>
    <build>
        <plugins>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>1.3.6</version>
                <executions>
                    <execution>
                        <id>default</id>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                        <configuration>
                            <tag>${project.version}</tag>
                        </configuration>
                    </execution>
                    <execution>
                        <id>push-as-latest</id>
                        <configuration>
                            <tag>latest</tag>
                        </configuration>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <repository>docker.nexus.somewhere/someone/something</repository>
                    <buildArgs>
                        <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
                    </buildArgs>
                    <useMavenSettingsForAuth>true</useMavenSettingsForAuth>
                </configuration>
                <dependencies>
<!-- from https://github.com/spotify/dockerfile-maven/issues/62#issuecomment-356368099 -->
                    <dependency>
                        <groupId>com.spotify</groupId>
                        <artifactId>docker-client</artifactId>
                        <classifier>shaded</classifier>
                        <version>8.11.1</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by lazam** [comment]
The issue still exists at 1.3.7, even with the docker config without https/http. The aforementioned version (1.3.3) works as expected without any changes in Docker client.

**Comment by codingtony** [comment]
Thanks @lazam for the workaround.

I confirm that works with 1.3.3 and do not work with 1.3.7

**Comment by nick-wellinghoff-sp** [comment]
had to revert to 1.3.3 to use AWS again as well.

**Comment by mmiglier** [comment]
Forcing the plugin to use docker client latest release (8.11.2) fixed ecr login issues to me

**Comment by tschutte** [comment]
@mmiglier Were you successful shading to the 8.11.2 docker client using plugin version 1.4.0 or an older version?

**Comment by mmiglier** [comment]
Using 1.4.0

**Comment by tschutte** [comment]
Thanks.  Seems none of these combinations are working for me on 1.4.0 and newer docker clients (on linux).  For now I've successfully reverted to 1.3.3 as well.

**Comment by josmora** [comment]
The solution suggested by @mmiglier  works for me using credentials into the pom.xml on the version 1.4.0

**Comment by mmiglier** [comment]
1.4.10 is still failing to push to ecr, and the above workaround is not working anymore. Rolling back to 1.4.0 + docker-client 8.11.2

**Comment by casper5822** [comment]
Same problem with my configuration :

plugin version 1.4.10 
docker-client:
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false
